=== Riverscapes/RaveAddIn/RaveAddIn/XML/XSD/project_explorer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Overall Structure  -->
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Name"/>
        <xs:element type="xs:string" name="Description" minOccurs="0"/>
        <xs:element type="xs:string" name="ProjectType"/>
        <xs:element type="NodeType" name="Node"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Allowable things to add to the map-->
  <xs:simpleType name="datatype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vector" />
      <xs:enumeration value="raster" />
      <xs:enumeration value="tile" />
      <xs:enumeration value="file" />
      <xs:enumeration value="tin" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Node: A one-off tree branch that has an xpath -->
  <xs:complexType name="NodeType">
    <xs:sequence>
      <xs:element type="xs:string" name="Tileservice" minOccurs="0"/>
      <xs:element type="ChildrenType" name="Children" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="optional"/>
    <xs:attribute type="datatype" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="symbology" use="optional"/>
  </xs:complexType>

  <!-- Repeaters: loop over xml node "arrays" -->
  <xs:complexType name="RepeaterType">
    <xs:sequence>
      <xs:choice>
        <xs:element type="NodeType" name="Node" maxOccurs="1"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="required"/>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

  <!--Children is basically just a bucket that can contain nodes and repeaters-->
  <xs:complexType name="ChildrenType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="NodeType" name="Node" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element type="RepeaterType" name="Repeater" minOccurs="1" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

</xs:schema>

=== Riverscapes/RaveAddIn/RaveAddIn/XML/hydro.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/XML/XSD/project_explorer.xsd">
  <Name>CHaMP Delft3D Hydraulic Model</Name>
  <ProjectType>Hydro</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">

      <Node label="Inputs">
        <Children collapsed="true">
          <Node label="Raw Survey Data">
            <Children>
              <Node label="Breaklines CAD DXF file" xpath="Inputs/Vector[@id='BreaklineDXF']" type="file" />
              <Node label="Survey Instrument File (*.mjf)" xpath="Inputs/InstrumentFile" type="file" />
              <Node label="Auxilary RAW Instrument File" xpath="Inputs/AuxInstrumentFile" type="file" />
            </Children>
          </Node>

          
        </Children>
      </Node>

      

    </Children>
  </Node>
</Project>

=== Riverscapes/RaveAddIn/RaveAddIn/XML/inundation.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD/project_explorer.xsd">
  <Name>Inundation Mapper</Name>
  <ProjectType>Inundation</ProjectType>
  <Node xpathlabel="Name">
    <Children>
      <Node label="Output">
        <Children>
          <Repeater label="Change Detections" xpath="Realizations/CDs">
            <Node xpathlabel="Name">
              <Children>
                <Node xpathlabel="Name" xpath="Vector[@id='in_change_01']" type="vector" symbology="Changes in inundation type" />
                <Repeater xpath="PDF">
                  <Node xpathlabel="Name" type="file" />
                </Repeater>
              </Children>
            </Node>
          </Repeater>
        </Children>
      </Node>
      <Node label="Mapping">
        <Children>
          <Repeater label="DCEs" xpath="Mapping/DCEs">
            <Node xpathlabel="Name">
              <Children>
                <Node xpathlabel="Name" xpath="Vector[@id='thalwegs_01']" type="vector" symbology="thalwegs" />
                <Node label="Dam Crests">
                  <Children>
                    <Node label="Dam state" xpath="Vector[@id='damcrests_01']" type="vector" symbology="dam_state" />
                    <Node label="Crest type" xpath="Vector[@id='damcrests_01']" type="vector" symbology="crests_type" />
                  </Children>
                </Node>
                <Node label="Inundation">
                  <Children>
                    <Node label="Inundation Types" xpath="Vector[@id='inundation_01']" type="vector" symbology="inundation_types" />
                    <Node label="Wetted Extent" xpath="Vector[@id='inundation_01']" type="vector" symbology="wetted_extent" />
                  </Children>
                </Node>
              </Children>
            </Node>
          </Repeater>
          <Node label="Riverscape">
            <Children>
              <Node xpathlabel="Name" xpath="Mapping/RS_Context/Vector[@id='vbcenterline_01']" type="vector" symbology="" />
              <Node xpathlabel="Name" xpath="Mapping/RS_Context/Vector[@id='valleybottom_01']" type="vector" symbology="valley_bottom" />
            </Children>
          </Node>
        </Children>
      </Node>
      <Node label="Inputs">
        <Children>
          <Node label="Imagery">
            <Children>
              <Node xpathlabel="Name" xpath="Inputs/Raster[@id='AP_01']" type="raster" symbology="ortho" />
              <Node xpathlabel="Name" xpath="Inputs/Raster[@id='AP_02']" type="raster" symbology="ortho" />
            </Children>
          </Node>
          <Node label="Context">
            <Children>
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='BRAT_01']" type="vector" symbology="BRAT" />
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='VBET_01']" type="vector" symbology="VBET" />
              <Node xpathlabel="Name" xpath="Inputs/DEM[@id='DEM_01']" type="raster" symbology="DEM" />
              <Node xpathlabel="Name" xpath="Inputs/Vector[@id='hillshade_01']" type="vector" symbology="hillshade" />
            </Children>
          </Node>
        </Children>
      </Node>
    </Children>
  </Node>
</Project>

=== Riverscapes/RaveAddIn/RaveAddIn/XML/rs_context.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD\project_explorer.xsd">
  <Name>Riverscapes Context</Name>
  <ProjectType>RSContext</ProjectType>
  <Node xpathlabel="Name" xpath="Realizations/RSContext">
    <Children collapsed="false">
      <Node label="Transportation">
        <Children>
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='Roads']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='Rail']" type="vector" symbology="railroads" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='Canals']" type="vector" symbology="canals_ditches" />
        </Children>
      </Node>
      <Node label="Hydrology">
        <Children>
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='NHDFlowline']" type="vector" symbology="flow_lines" />
          <Node label="Drainage Area (SqKm)" xpath="Realizations/RSContext/Vector[@id='NHDFlowline']" type="vector" symbology="UpstreamDrainageArea" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='NHDPlusCatchment']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='NHDArea']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='NHDWaterbody']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='WBDHU2']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='WBDHU4']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='WBDHU6']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='WBDHU8']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='WBDHU10']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='WBDHU12']" type="vector" symbology="" />
        </Children>
      </Node>
      <Node label="Topography">
        <Children>
          <Node xpathlabel="Name" xpath="Realizations/RSContext/DEM" type="raster" symbology="dem" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Raster[@id='HILLSHADE']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Raster[@id='SLOPE']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Raster[@id='FA']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Raster[@id='DA']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Raster[@id='HAND']" type="raster" symbology="" />
        </Children>
      </Node>
      <Node label="Ownership">
        <Children>
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Vector[@id='Ownership']" type="vector" symbology="" />
        </Children>
      </Node>
      <Node label="Vegetation">
        <Children>
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Raster[@id='EXVEG']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Realizations/RSContext/Raster[@id='HISTVEG']" type="raster" symbology="" />
        </Children>
      </Node>
    </Children>
  </Node>
</Project>

=== Riverscapes/RaveAddIn/RaveAddIn/XML/rvd.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/XML/XSD/project_explorer.xsd">
  <Name>RVD</Name>
  <ProjectType>RVD</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">
      <Node xpathlabel="Name" xpath="Realizations/RVD/Outputs/HTMLFile" type="file" />
      <Node label="Inputs" xpath="Realizations/RVD/Inputs">
        <Children>
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='FLOWLINES']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='FLOW_AREA']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='WATERBODIES']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='VALLEY_BOTTOM']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Raster[@id='EXVEG']" type="raster" symbology="" />
          <Node xpathlabel="Name" xpath="Raster[@id='HISTVEG']" type="raster" symbology="" />
        </Children>
      </Node>
      <Node label="Intermediates" xpath="Realizations/RVD/Intermediates">
        <Children collapsed="true">
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='CLEANED']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='NETWORK']" type="vector" symbology="" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='THIESSEN']" type="vector" symbology="" />
        </Children>
      </Node>
      <Node label="Outputs" xpath="Realizations/RVD/Outputs">
        <Children>
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='SEGMENTED']" type="vector" symbology="" />
        </Children>
      </Node>
    </Children>
  </Node>
</Project>

=== Riverscapes/RaveAddIn/RaveAddIn/XML/rca.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSD/project_explorer.xsd">
    <Name>RCA</Name>
    <ProjectType>RCA</ProjectType>
    <Node xpathlabel="Name">
        <Children>
            <Repeater label="Realizations" xpath="Realizations/RCA">
                <!-- this is a template for how realizations should render-->
                <Node xpathlabel="Name">
                    <Children collapsed="false">
                        <Node label="Inputs" xpath="Inputs">
                            <Children>
                                <Node xpathlabel="Name" xpath="ExistingVegetation" type="raster" symbology="">
                                    <Children>
                                        <Repeater label="Existing Cover Rasters" xpath="ExistingRasters">
                                            <Node xpathlabel="Name" xpath="Raster" type="raster" symbology="" />
                                        </Repeater>
                                    </Children>
                                </Node>
                                <Node xpathlabel="Name" xpath="HistoricVegetation" type="raster" symbology="">
                                    <Children>
                                        <Repeater label="Historic Cover Rasters" xpath="HistoricRasters">
                                            <Node xpathlabel="Name" xpath="Raster" type="raster" symbology="" />
                                        </Repeater>
                                    </Children>
                                </Node>
                                <Node xpathlabel="Name" xpath="DrainageNetworks/Network" type="vector" symbology="">
                                    <Children>
                                        <Node xpathlabel="Name" xpath="ThiessenPolygons" type="vector" symbology="" />
                                    </Children>
                                </Node>
                                <Node xpathlabel="Name" xpath="FragmentedValleyBottom" type="vector" symbology="" />
                                <Node xpathlabel="Name" xpath="LargeRiverPolygon" type="vector" symbology="" />
                            </Children>
                        </Node>
                        <Node label="Analyses" xpath="Analyses">
                            <Children>
                                <Node label="Outputs" xpath="Analysis/Outputs">
                                    <Children>
                                        <Node xpathlabel="Name" xpath="Vector" type="vector" symbology="vector_RCA" />
                                    </Children>
                                </Node>
                            </Children>
                        </Node>
                    </Children>
                </Node>
            </Repeater>
        </Children>
    </Node>
</Project>

=== Riverscapes/RaveAddIn/RaveAddIn/XML/gut.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/XML/XSD/project_explorer.xsd">
  <Name>GUT</Name>
  <ProjectType>GUT</ProjectType>
  <Node xpathlabel="Name">
    <Children>
      <Repeater label="Realizations" xpath="Realizations/GUT">
        <Node xpathlabel="Name">
          <Children collapsed="true">
            <Node label="Inputs" xpath="Inputs">
              <Children collapsed="true">
                <Node xpathlabel="Name" xpath="Centerline[@id='BFCL']" type="vector" symbology="in_BankfullCenterline" />
                <Node label="Bankfull Cross Sections QA/QC " xpath="CrossSections[@id='BFXS']" type="vector" symbology="XS_qaqc" />
				<Node label="Bankfull Cross Sections Type" xpath="CrossSections[@id='BFXS']" type="vector" symbology="XS_type" />
                <Node xpathlabel="Name" xpath="Extent[@id='BFEX']" type="vector" symbology="in_BankfullExtent" />
                <Node xpathlabel="Name" xpath="Islands[@id='BFI']" type="vector" symbology="bfIlsands" />
                <Node xpathlabel="Name" xpath="ChannelUnits[@id='CU']" type="vector" symbology="cu_UnitNum" />
                <Node xpathlabel="Name" xpath="ChannelUnits[@id='CU_1']" type="vector" symbology="Channel_Units_Field" transparency="40"/>
                <Node xpathlabel="Name" xpath="DEM" type="raster" symbology="dem" transparency="40" />
                <Node label="Thalweg Type" xpath="Thalweg" type="vector" symbology="in_Thalwegs_Type" />
				<Node label="Thalweg Channel" xpath="Thalweg" type="vector" symbology="in_Thalwegs_Channel"/>
                <Node xpathlabel="Name" xpath="Centerline[@id='WCL']" type="vector" symbology="in_WaterCenterline" />
                <Node label="Wetted Cross Sections QA/QC" xpath="CrossSections[@id='WXS']" type="vector" symbology="XS_qaqc" />
				<Node label="Wetted Cross Sections Type" xpath="CrossSections[@id='WXS']" type="vector" symbology="XS_type" />
                <Node xpathlabel="Name" xpath="Extent[@id='WEEX']" type="vector" symbology="in_WaterExtent" transparency="40" />
                <Node xpathlabel="Name" xpath="Islands[@id='WI']" type="vector" symbology="wetIslands" />
              </Children>
            </Node>
            <Node label="Evidence" xpath="EvidenceLayers">
              <Children collapsed="true">
                <Node xpathlabel="Name" xpath="Raster[@id='ID']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID']" type="vector" symbology=""/>
                <Node xpathlabel="Name" xpath="Raster[@id='ID_1']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Slope[@id='BFSLOPE']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Raster[@id='ID_2']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Raster[@id='ID_3']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Slope[@id='BFSSSMOOTH']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID_1']" type="vector" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID_2']" type="vector" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID_3']" type="vector" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID_4']" type="vector" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID_5']" type="vector" symbology=""/>
                <Node xpathlabel="Name" xpath="DEM[@id='DEMSMOOTH']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Raster[@id='ID_5']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Raster[@id='ID_6']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Raster[@id='ID_7']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Raster[@id='ID_8']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Raster[@id='ID_9']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Slope[@id='ICDEMSLOPE']" type="raster" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID_7']" type="vector" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID_8']" type="vector" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID_9']" type="vector" symbology=""/>
                <Node xpathlabel="Name" xpath="Vector[@id='ID_10']" type="vector" symbology=""/>
              </Children>
            </Node>
            <Repeater label="Analyses" xpath="Analyses/Analysis">
              <Node xpathlabel="Name">
                <Children collapsed="true">
                  <Node xpathlabel="Name" xpath="Outputs/Tier1" type="vector" symbology=""/>
                  <Node xpathlabel="Name" xpath="Outputs/Tier2[@id='Tier2']" type="vector" symbology=""/>
                  <Node xpathlabel="Name" xpath="Outputs/Tier2[@id='Tier2_1']" type="vector" symbology=""/>
                  <Node xpathlabel="Name" xpath="Outputs/Tier3[@id='Tier3']" type="vector" symbology=""/>
                  <Node xpathlabel="Name" xpath="Outputs/Tier3[@id='Tier3_1']" type="vector" symbology=""/>
                  <Node xpathlabel="Name" xpath="Outputs/Tier3[@id='Tier3_2']" type="vector" symbology=""/>
                  <Node xpathlabel="Name" xpath="Outputs/Tier1[@id='Tier3_3']" type="vector" symbology=""/>
                </Children>
              </Node>
            </Repeater>
          </Children>
        </Node>
      </Repeater>
    </Children>
  </Node>
</Project>

=== Riverscapes/RaveAddIn/RaveAddIn/XML/pyBRAT.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/XML/XSD/project_explorer.xsd">
  <Name>pyBRAT</Name>
  <ProjectType>pyBRAT</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">
      <Node label="Outputs" xpath="Realizations/BRAT/Outputs">
        <Children>
          <Node label="Validation">
            <Children>
              <Node label="Surveyed Beaver Dam Locations"/>
              <Node label="Predicted Dam Density vs. Surveyed Dam Density"/>
              <Node label="Percent of Historic Dam Capacity Remaining"/>
							<Node label="Current Beaver Dam Management Strategies"/>
            </Children>
          </Node>
					<Node label="Capacity">
						<Children>
							<Node label="Existing Capacity">
								<Children>
									<Node label="Existing Dam Capacity"/>
									<Node label="Existing Dam Size"/>
								</Children>
							</Node>
							<Node label="Historic Capacity">
								<Children>
									<Node label="Historic Dam Capacity"/>
									<Node label="Historic Dam Size"/>
								</Children>
							</Node>
						</Children>
					</Node>
					<Node label="Management">
						<Children>
							<Node label="Unsuitable or Limited Opportunities"/>
							<Node label="Risk of Undesirable Dams"/>
							<Node label="Restoration or Conservation Opportunities"/>
						</Children>
					</Node>
        </Children>
      </Node>
      <Node label="Intermediates" xpath="Realizations/BRAT/Outputs">
        <Children>
          <Node label="Perennial"/>
					<Node label="Anabranch Handler"/>
          <Node label="Topographic Index">
            <Children>
              <Node label="Slope"/>
              <Node label="Drainage Area"/>
            </Children>
          </Node>
          <Node label="Hydrology">
            <Children>
              <Node label="High Flow Stream Power"/>
              <Node label="Base Flow Stream Power"/>
            </Children>
          </Node>
          <Node label="Overall Vegetation Dam Capacity">
            <Children>
              <Node label="Existing Veg Dam Building Capacity"/>
              <Node label="Historic Veg Dam Building Capacity"/>
            </Children>
          </Node>
          <Node label="Anthropogenic Intermediates">
            <Children>
              <Node label="Distance to Canals/Ditches"/>
							<Node label="Distance to Closest Infrastructure"/>
							<Node label="Distance to Points of Diversion"/>
							<Node label="Distance to Railroad"/>
							<Node label="Distance to Railroad in Valley Bottom"/>
							<Node label="Distance to Road"/>
              <Node label="Distance to Road Crossing"/>
              <Node label="Distance to Road in Valley Bottom"/>
							<Node label="Land Ownership per Reach"/>
              <Node label="Land Use Intensity"/>
							<Node label="Priority Beaver Translocation Areas"/>
            </Children>
          </Node>
          <Node label="Buffers">
            <Children>
              <Node label="30m Buffer"/>
              <Node label="100m Buffer"/>
            </Children>
          </Node>		  
        </Children>
      </Node>
      <Node label="Inputs" xpath="Realizations/BRAT/Inputs">
        <Children>
					<Node label="Anthropogenic Layers">
            <Children>
							<Node label="Canals">
								<Children>
									<Node label="Provisional Points of Diversion"/>
									<Node label="Canals and Ditches"/>
								</Children>
							</Node>
							<Node label="Valley Bottom">
								<Children>
									<Node label="Valley Bottom Outline"/>
									<Node label="Valley Bottom Fill"/>
								</Children>
							</Node>
              <Node label="Railroads"/>
              <Node label="Roads"/>
              <Node label="Land Ownership"/>
              <Node label="Land Use"/>
            </Children>
          </Node>
					<Node label="Vegetation">
            <Children>
							<Node label = "Existing Vegetation Dam Capacity">
								<Children>
									<Node label="Veg Type - EVT Type"/>
									<Node label="Veg Type - EVT Name"/>
									<Node label="Veg Type - EVT Class"/>
									<Node label="Existing Vegetation Suitability for Beaver Dam Building"/>
									<Node label="Existing Riparian"/>
								</Children>
							</Node>
							<Node label = "Historic Vegetation Dam Capacity">
								<Children>
									<Node label="Veg Type - BPS Type"/>
									<Node label="Veg Type - BPS Name"/>
									<Node label="Historic Vegetation Suitability for Beaver Dam Building"/>
									<Node label="Historic Riparian"/>
								</Children>
							</Node>							
            </Children>
          </Node>
          <Node label="Topography">
            <Children>
              <Node label="Flow Accumulation"/>
              <Node label="Slope"/>
              <Node label="DEM"/>
              <Node label="Hillshade"/>
            </Children>
          </Node>
        </Children>
      </Node>
    </Children>
  </Node>
</Project>
