=== Riverscapes/RaveAddIn/RaveAddIn/XML/XSD/project_explorer.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Overall Structure  -->
  <xs:element name="Project">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="Name"/>
        <xs:element type="xs:string" name="Description" minOccurs="0"/>
        <xs:element type="xs:string" name="ProjectType"/>
        <xs:element type="NodeType" name="Node"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <!--Allowable things to add to the map-->
  <xs:simpleType name="datatype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="vector" />
      <xs:enumeration value="raster" />
      <xs:enumeration value="tile" />
      <xs:enumeration value="file" />
      <xs:enumeration value="tin" />
    </xs:restriction>
  </xs:simpleType>

  <!-- Node: A one-off tree branch that has an xpath -->
  <xs:complexType name="NodeType">
    <xs:sequence>
      <xs:element type="xs:string" name="Tileservice" minOccurs="0"/>
      <xs:element type="ChildrenType" name="Children" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="optional"/>
    <xs:attribute type="datatype" name="type" use="optional"/>
    <xs:attribute type="xs:string" name="symbology" use="optional"/>
  </xs:complexType>

  <!-- Repeaters: loop over xml node "arrays" -->
  <xs:complexType name="RepeaterType">
    <xs:sequence>
      <xs:choice>
        <xs:element type="NodeType" name="Node" maxOccurs="1"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute type="xs:string" name="label" use="optional"/>
    <xs:attribute type="xs:string" name="xpathlabel" use="optional"/>
    <xs:attribute type="xs:string" name="xpath" use="required"/>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

  <!--Children is basically just a bucket that can contain nodes and repeaters-->
  <xs:complexType name="ChildrenType">
    <xs:choice maxOccurs="unbounded">
      <xs:element type="NodeType" name="Node" minOccurs="1" maxOccurs="unbounded"/>
      <xs:element type="RepeaterType" name="Repeater" minOccurs="1" maxOccurs="unbounded"/>
    </xs:choice>
    <xs:attribute type="xs:boolean" name="collapsed" use="optional"/>
  </xs:complexType>

</xs:schema>

=== Riverscapes/RaveAddIn/RaveAddIn/XML/vbet.xml
<?xml version="1.0" encoding="utf-8" ?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/XML/XSD/project_explorer.xsd">
  <Name>VBET</Name>
  <ProjectType>VBET</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">
      <Node label="Inputs">
        <Children>
          <Node label="Hydrography (NHD HR+)">
            <Children>

<Node xpathlabel="Name" xpath="Realizations/VBET/Intermediates/Vector[@id='VBET_NETWORK']" type="vector" symbology="" />
              <Node label="Full NHD HR+ Drainage Network" xpath="Realizations/VBET/Inputs/Vector[@id='FLOWLINES']" type="vector" symbology="flow_lines" />

<Node label="Perrenial Drainage Network" xpath="Realizations/VBET/Inputs/Vector[@id='FLOWLINES']" type="vector" symbology="nhdperrenial" />

<Node label="Intermittent Drainage Network" xpath="Realizations/VBET/Inputs/Vector[@id='FLOWLINES']" type="vector" symbology="nhdintermittent" />

<Node label="Ephemeral Drainage Network" xpath="Realizations/VBET/Inputs/Vector[@id='FLOWLINES']" type="vector" symbology="nhdephemeral" />

<Node label="Network - Upstream Drainage Network" xpath="Realizations/VBET/Inputs/Vector[@id='FLOWLINES']" type="vector" symbology="upstreamdrainagearea" />
              <Node label="River Polygons (NHD Area)" xpath="Realizations/VBET/Inputs/Vector[@id='FLOW_AREA']" type="vector" symbology="nhdarea" />																						             			</Children>
          </Node>
          <Node label="Lines of Evidence">
            <Children>
              <Node label="Slope Analysis" xpath="Realizations/VBET/Inputs/Raster[@id='SLOPE_RASTER']" type="raster" symbology="slope" />
              <Node label="Height Above Nearest Drainage" xpath="Realizations/VBET/Inputs/Raster[@id='HAND_RASTER']" type="raster" symbology="hand" />
              <Node label="Active Channel" xpath="Realizations/VBET/Intermediates/Raster[@id='CHANNEL_RASTER']" type="raster" symbology="active_channel" />
            </Children>
          </Node>
          <Node label="Topography">
            <Children>
              <Node xpathlabel="Name" xpath="Realizations/VBET/Inputs/Raster[@id='HILLSHADE']" type="raster" symbology="" />
            </Children>
          </Node>
        </Children>
      </Node>
      <Node label="Intermediates">
        <Children collapsed="true">
          <Node label="50% Threshold Raw VBET" xpath="Realizations/VBET/Intermediates/Vector[@id='THRESH_50']" type="vector" symbology="threshold_50" />
          <Node label="60% Threshold Raw VBET" xpath="Realizations/VBET/Intermediates/Vector[@id='THRESH_60']" type="vector" symbology="threshold_60" />
          <Node label="70% Threshold Raw VBET" xpath="Realizations/VBET/Intermediates/Vector[@id='THRESH_70']" type="vector" symbology="threshold_70" />
          <Node label="80% Threshold Raw VBET" xpath="Realizations/VBET/Intermediates/Vector[@id='THRESH_80']" type="vector" symbology="threshold_80" />
          <Node label="90% Threshold Raw VBET" xpath="Realizations/VBET/Intermediates/Vector[@id='THRESH_90']" type="vector" symbology="threshold_90" />
          <Node label="100% Threshold Raw VBET" xpath="Realizations/VBET/Intermediates/Vector[@id='THRESH_100']" type="vector" symbology="threshold_100" />
          <Node xpathlabel="Name" xpath="Realizations/VBET/Intermediates/Raster[@id='EVIDENCE']" type="raster" symbology="" />
        </Children>
      </Node>
      <Node label="Analyses">
        <Children>
          <Node label="Outputs">
            <Children>
              <Node xpathlabel="Name" xpath="Realizations/VBET/Outputs/Vector[@id='VBET_50']" type="vector" symbology="vbet" />
              <Node xpathlabel="Name" xpath="Realizations/VBET/Outputs/Vector[@id='VBET_60']" type="vector" symbology="vbet" />
              <Node xpathlabel="Name" xpath="Realizations/VBET/Outputs/Vector[@id='VBET_70']" type="vector" symbology="vbet" />
              <Node xpathlabel="Name" xpath="Realizations/VBET/Outputs/Vector[@id='VBET_80']" type="vector" symbology="vbet" />
              <Node xpathlabel="Name" xpath="Realizations/VBET/Outputs/Vector[@id='VBET_90']" type="vector" symbology="vbet" />
              <Node xpathlabel="Name" xpath="Realizations/VBET/Outputs/Vector[@id='VBET_100']" type="vector" symbology="vbet" />
            </Children>
          </Node>
        </Children>
      </Node>
    </Children>
  </Node>
</Project>

=== Riverscapes/RaveAddIn/RaveAddIn/XML/confinement.xml
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/Riverscapes/RaveAddIn/master/RaveAddIn/XML/XSD/project_explorer.xsd">
  <Name>Confinement</Name>
  <ProjectType>CONFINEMENT</ProjectType>
  <Node xpathlabel="Name">
    <Children collapsed="false">
      <Node xpathlabel="Name" xpath="Realizations/Confinement/Outputs/HTMLFile" type="file" />
      <Node label="Inputs" xpath="Realizations/Confinement/Inputs">
        <Children>
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='FLOWLINES']" type="vector" symbology="flow_lines" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='CONFINING_POLYGON']" type="vector" symbology="" />
        </Children>
      </Node>
      <Node label="Outputs" xpath="Realizations/Confinement/Outputs">
        <Children>
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='CONFINEMENT_RAW']" type="vector" symbology="confinement_raw" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='CONFINEMENT_MARGINS']" type="vector" symbology="confinement_margins" />
          <Node xpathlabel="Name" xpath="Geopackage/Layers/Vector[@id='CONFINEMENT_RATIO']" type="vector" symbology="confinement_ratio" />
        </Children>
      </Node>

    </Children>
  </Node>
</Project>
